[package]
name = "botwrapper"
version = "0.1.0"
authors = ["memoryleak47 <memoryleak47@protonmail.ch>"]

[dependencies]
time = "0.1"
botfather = { git = "https://github.com/ml47-srl/b.3-botfather.git" }
